### ISSUE TITLE
Sorter sometimes doesn't work 

### ISSUE THREAD

**Issue by Asakushen** [hubastard/nebula#498] opened 2022-01-14 12:06 UTC
Sorters do not output items from furnaces or crafting tables to the conveyor belt, causing furnace items to pile up. When this bug is encountered, the sorter must be manually removed and installed back in for it to work properly.

**Comment by sp00ktober** [comment] 2022-01-15 14:19
duplicate of this one #336

**Closed by sp00ktober** 2022-01-15 14:19 UTC

**Comment by starfi5h** [comment] 2022-01-17 16:37
I think it may be similar to #256, which reoccurs in the current version. In my test the host didn't send NewSetInserterInsertTargetPacket and NewSetInserterPickTargetPacket after client leave the planet.
