### ISSUE TITLE
Player lighting doesn't affect other players

### ISSUE THREAD

**Issue by Flapperkewiet** [hubastard/nebula#29] opened 2021-03-05 22:47 UTC
When it's dark and two player are standing beside each other, they don't receive lighting from each other, making the other player very dark.

**Comment by Flapperkewiet** [comment] 2021-03-06 16:20
![DSP No Light](https://user-images.githubusercontent.com/28689810/110213373-09d8c380-7ea0-11eb-8c69-b660ea2f5320.png)

As you can see, the remote player doesn't have a light source. I tried looking, but couldn't find where the light of the player is, as even disabling the player, the light remains. If anyone can find it, let me know.

**Comment by Baldie-dev** [comment] 2021-03-20 09:37
It seems that Guiding light is being toggled in UIGameMenu by:
`public void OnDfLightButtonClick()
	{
		PostEffectController.headlight = !PostEffectController.headlight;
	}`

And then actual light is renedered by shader in PostEffectController:
`Vector3 position = mainPlayer.position;
Shader.SetGlobalVector("_Global_PointLightPos", new Vector4(position.x, position.y, position.z, 1f));
`

**Comment by Baldie-dev** [comment] 2021-03-20 09:46
But since the light is made by Shader using a global variable, I am not sure how to add a second instance of the light. Maybe a workaround would be attaching a light source above the mech model, but that would not look that nice.

**Comment by Flapperkewiet** [comment] 2021-03-20 10:33
I'm don't know how unity stores shaders, but maybe we can extract the shader code, modify it, and then reassign it? Unless ofcourse only the compiled shader code is stored.

**Comment by Baldie-dev** [comment] 2021-03-20 12:43
I believe you would have to somehow duplicate the shader and change the name of the input variable. Shaders need to be compiled beforehand if I am not mistaken.

- One solution could be to create multiple shaders and just change the input variable to "`_Global_PointLightPos2`", "`_Global_PointLightPos3`", etc... and assign it to each player. Bur, I cannot guess how much effort would this take.

Maybe some Guru will have a better idea of how to solve this? :D

**Comment by hubastard** [comment] 2021-03-20 14:48
The easiest way would be to try adding a point light gameobject as a child of the remote players and look if it works. If it doesn't, we can add and load custom shader by using asset bundles.

**Comment by Flapperkewiet** [comment] 2021-03-20 17:18
I was able to extract 199 shader files files from the assets, but they are semi-compiled I believe, I found 3698 references to `_Global_PointLightPos`  spread over 44 files. On closer inspection, the header data of the shaders seem to be somewhat intact, but all the actual shader-code is always in a single main function.  All of the variable names are also stripped.

So in essence, i have 200 files of each between 1 and 10 thousand lines of:


					    u_xlat11.xyz = u_xlat2.xyz + vec3(-1.0, -1.0, -1.0);
					    u_xlat11.xyz = u_xlat0.xxx * u_xlat11.xyz + vec3(1.0, 1.0, 1.0);
					    u_xlat8.xyz = u_xlat8.xyz * u_xlat11.xyz;
					    u_xlat28.x = u_xlat28.x * u_xlat42 + 0.0318309888;
					    u_xlat8.xyz = u_xlat28.xxx * u_xlat8.xyz;
					    u_xlat11.xyz = u_xlat3.xyz + vec3(u_xlat46);
					    u_xlat8.xyz = u_xlat8.xyz * u_xlat11.xyz;
					    if(u_xlatb44){
					        u_xlat28.x = u_xlat45 + -20.0;
					        u_xlat42 = u_xlat28.x;
					        u_xlat42 = clamp(u_xlat42, 0.0, 1.0);
					        u_xlat42 = u_xlat50 * u_xlat42;
					        u_xlat4.xyz = (-u_xlat4.xyz) * u_xlat28.xxx + _Global_PointLightPos.xyz;
					        u_xlat28.x = dot(u_xlat4.xyz, u_xlat4.xyz);
					        u_xlat28.x = sqrt(u_xlat28.x);
					        u_xlat44 = (-u_xlat28.x) + 40.0;
					        u_xlat44 = u_xlat44 * 0.0250000004;

**Comment by hubastard** [comment] 2021-03-20 17:26
I've tested adding Light to the player but there is a big artefact.
![Capture](https://user-images.githubusercontent.com/69216913/111880106-cd1cca00-897f-11eb-9cca-0b8a2a3d2fd9.PNG)

What we could probably do, is create our own shader for remote player lighting and add a custom post effect of this shader on the main camera.

**Comment by Baldie-dev** [comment] 2021-03-20 18:26
I also tried it with multiple different settings for the spotlight and the artefact disappeared. But it seems that light only affects the mech and not the ground. Probably also something with culling settings. So, trial and error... here we go.

**Comment by Baldie-dev** [comment] 2021-03-20 18:46
Nevermind, it was not just inside the view of the camera, but it is still visible in the planetary view. This is not a good way how to do it :(

![e](https://i.ibb.co/sCcmsm3/aa.png)

**Comment by Baldie-dev** [comment] 2021-03-20 22:50
I have done some digging and I more or less understand how it is done now. The light effect is done by a global variable that is used in all shaders for all materials that receives this light. In this way, they can control how this light will interact with different materials (leaves, water, surface, etc.). Since it is used in 44 shaders in almost 44 different ways, it is not possible to do it in the same way.

I am still trying to find out, what is causing this artifact and if there is some way how to bypass it.

@hubastard: If you attach the shader to the main camera, you can only control the brightness of the pixels around the player right? I am not sure if you would be able to do some projection onto the surface to highlight only the surface. Otherwise, I think you would be also highlighting the pixels that belong to "air", so if players rotate the camera close to the horizon. There will be always a circle of highlighted pixels around the player, right?

**Comment by hubastard** [comment] 2021-03-20 23:18
Yeah I think you are right.. I will try to see if I can find a way to get almost the same look somehow..

**Comment by Baldie-dev** [comment] 2021-03-21 12:26
Regarding the initial issue, that one player does not receive light from another player. I think it is caused by some issues with the model\shaders on the model. I was checking it, but I am not exactly sure why.

From each player's perspective, his model receives more lights than models of other players so all other players look more darker.

The arrow shows from which player's perspective I have made the screenshot.
![light](https://i.imgur.com/yXLAF2H.png)

**Comment by hubastard** [comment] 2021-08-28 01:25
Will not fix. Since this would require changing the entire shader code of the game.

**Closed by hubastard** 2021-08-28 01:25 UTC
Labels: bug, help wanted
