### ISSUE TITLE
Clients were able to stack research labs above the current stack limit.

### ISSUE THREAD

**Issue by hubastard** [hubastard/nebula#115] opened 2021-04-09 01:53 UTC
During our playthrough, a client was able to stack 6 labs even if the the limit was 3.

**Comment by hubastard** [comment] 2021-04-09 04:15
@sp00ktober We would need to test it again while being 3 players, I think that it was related to the desync issue that I fixed https://github.com/hubastard/nebula/commit/aeb063e8b0071fc4a977441432edabbb39c5b7bf

**Comment by hubastard** [comment] 2021-04-09 04:21
Ok no, the issue is still there. I've been able to replicate it but only on a client not the host.

**Comment by Baldie-dev** [comment] 2021-04-09 20:48
I am checking it now :)

**Comment by Baldie-dev** [comment] 2021-04-09 21:11
Hmm, i have ordered additional RAM :D 3rd instance is crashing with out of memory errors.
But I am not able to reproduce it with client and host alone :( the stack level 3 should be base without any research techs unlocked. I am not sure how it can increase on its own :(

**Comment by Baldie-dev** [comment] 2021-04-09 21:12
It is constant "labLevel" in GameHistoryData object, that is being synced by import/export functionality. Hmmm

**Comment by hubastard** [comment] 2021-04-09 23:41
In my test it took a maybe a minute of building / destroying before I was able to reproduce the issue. When the issue occurred, I was building 2 stacks at the same time alternating the building from one tower to the other. Once it "broke" it was causing the issue 100% of the time. But it took some time before

**Comment by hubastard** [comment] 2021-04-09 23:41
I'll try to reproduce the issue and make a video, maybe its a vanilla bug

**Comment by Baldie-dev** [comment] 2021-04-10 08:36
I think there will be some external factor to it. I was trying multiple combinations of destroying and building new levels from different clients and host, but no luck with reproducing it. I will check it from the code point of view, how this can happens:
![image](https://user-images.githubusercontent.com/79051050/114263953-7cc9e280-99e8-11eb-9352-6b8730977955.png)

**Comment by hubastard** [comment] 2021-04-10 15:12
Was finally able to replicate this on video:
https://youtu.be/l1UG7pdzkKY

**Comment by Baldie-dev** [comment] 2021-04-13 23:19
This should be fixed now :) After we do another test, we can close it.

**Closed** 2021-04-17 15:23 UTC
Labels: bug, close after retest
