### ISSUE TITLE
After using the nebula, the archive has an error

### ISSUE THREAD

**Issue by shoucandanghehe** [hubastard/nebula#381] opened 2021-07-19 16:50 UTC
When the online archive reached a certain level, the game started to report errors. After deleting all mods and using a single machine to load the archive, the error remains.
Is it possible that nebula caused the archive damage?
[log.txt](https://github.com/hubastard/nebula/files/6842604/log.txt)

**Comment by shoucandanghehe** [comment] 2021-07-19 17:23
I demolished all the buildings on a planet and re-entered the archive. The error report stopped. Let me further rule out what building caused the error.

**Comment by PhantomGamers** [comment] 2021-07-21 08:28
This is related to #336, likely caused by upgrading sorters.

**Comment by shoucandanghehe** [comment] 2021-07-21 08:32
> This is related to #336, likely caused by upgrading sorters.

Ah, we also encountered this bug. However, there are too many buildings on the planet I archived, and it is difficult to rule out further. Do you need to archive for testing?

**Comment by PhantomGamers** [comment] 2021-07-21 08:34
> Do you need to archive for testing?

No, we have a few different saves with this issue, it's just really difficult to figure out what is causing it 😅
Thank you though!

**Comment by shoucandanghehe** [comment] 2021-07-21 08:36
Ok.

**Comment by shoucandanghehe** [comment] 2021-07-29 14:55
It should be some broken sorters or buildings that caused the error. In the game, it looks like a sorter installed in reverse or a transparent building. You can use the scope removal function to fix this problem)

**Comment by sp00ktober** [comment] 2022-01-02 18:04
Closed in favor of #336

**Closed by sp00ktober** 2022-01-02 18:04 UTC
Labels: bug
